### ISSUE TITLE
Chapter 1, example 09, book version doesn't print the count

### ISSUE THREAD

**Issue by madwizard** [madwizard/k_und_r#1]
The book version (page 18) that I have is:

```
#include <stdio.h>

main()
{
    long nc;

    nc = 0;
    while(getchar() != EOF)
        ++nc;
   printf("%ld\n",nc);
}
```

That makes printf() call outside the while loop. I don't know how to trigger EOF without terminating the program, effectively not getting the character count printed. 

1. Check if maybe there's an errata.
2. Check Polish translation.

**Comment by leafnode** [comment]
ctrl+d
